return {
 ["htmlfiles"]={ "export-010-div.html" },
 ["htmlroot"]="export-010-div.html",
 ["identifier"]="9aa756b9-499a-a62b-df7a-665351af9690",
 ["imagefile"]="styles/export-010-images.css",
 ["imagepath"]="images",
 ["images"]={
  ["image>1"]={
   ["element"]="image",
   ["height"]="29.639pt",
   ["hover"]="",
   ["id"]="export-010-image-1",
   ["name"]="export-010-exported-1.svg",
   ["namespace"]="",
   ["page"]=1,
   ["url"]="../images/export-010-exported-1.svg",
   ["used"]="export-010-exported-1.svg",
   ["width"]="137.961pt",
  },
  ["image>2"]={
   ["element"]="image",
   ["height"]="15.696pt",
   ["hover"]="",
   ["id"]="export-010-image-2",
   ["name"]="export-010-exported-2.svg",
   ["namespace"]="",
   ["page"]=1,
   ["url"]="../images/export-010-exported-2.svg",
   ["used"]="export-010-exported-2.svg",
   ["width"]="131.858pt",
  },
  ["image>3"]={
   ["element"]="image",
   ["height"]="27.351pt",
   ["hover"]="",
   ["id"]="export-010-image-3",
   ["name"]="export-010-exported-3.svg",
   ["namespace"]="",
   ["page"]=1,
   ["url"]="../images/export-010-exported-3.svg",
   ["used"]="export-010-exported-3.svg",
   ["width"]="23.639pt",
  },
 },
 ["language"]="en",
 ["metadata"]={},
 ["name"]="export-010",
 ["stylepath"]="styles",
 ["styles"]={ "export-010-defaults.css", "export-010-images.css", "export-010-fonts.css", "export-010-styles.css" },
 ["title"]="export-010",
 ["xhtmlfiles"]={ "export-010-tag.xhtml" },
 ["xmlfiles"]={ "export-010-raw.xml" },
}