return {
 ["htmlfiles"]={ "symbolsets-001-div.html" },
 ["htmlroot"]="symbolsets-001-div.html",
 ["identifier"]="53f1329b-4c77-ab52-11bc-47efba5a066c",
 ["imagefile"]="styles/symbolsets-001-images.css",
 ["imagepath"]="images",
 ["images"]={
  ["image>1"]={
   ["element"]="image",
   ["height"]="14.474pt",
   ["hover"]="",
   ["id"]="symbolsets-001-image-1",
   ["name"]="symbolsets-001-exported-1.svg",
   ["namespace"]="",
   ["page"]=1,
   ["url"]="../images/symbolsets-001-exported-1.svg",
   ["used"]="symbolsets-001-exported-1.svg",
   ["width"]="36.580pt",
  },
  ["image>2"]={
   ["element"]="image",
   ["height"]="14.474pt",
   ["hover"]="",
   ["id"]="symbolsets-001-image-2",
   ["name"]="symbolsets-001-exported-2.svg",
   ["namespace"]="",
   ["page"]=1,
   ["url"]="../images/symbolsets-001-exported-2.svg",
   ["used"]="symbolsets-001-exported-2.svg",
   ["width"]="42.505pt",
  },
 },
 ["language"]="en",
 ["metadata"]={},
 ["name"]="symbolsets-001",
 ["stylepath"]="styles",
 ["styles"]={ "symbolsets-001-defaults.css", "symbolsets-001-images.css", "symbolsets-001-fonts.css", "symbolsets-001-styles.css" },
 ["title"]="symbolsets-001",
 ["xhtmlfiles"]={ "symbolsets-001-tag.xhtml" },
 ["xmlfiles"]={ "symbolsets-001-raw.xml" },
}