return {
 ["htmlfiles"]={ "simple-001-div.html" },
 ["htmlroot"]="simple-001-div.html",
 ["identifier"]="77a9406f-4f73-b418-3544-cb391309f556",
 ["imagefile"]="styles/simple-001-images.css",
 ["imagepath"]="images",
 ["images"]={
  ["image>1"]={
   ["element"]="image",
   ["height"]="17.441pt",
   ["hover"]="",
   ["id"]="simple-001-image-1",
   ["name"]="simple-001-exported-1.svg",
   ["namespace"]="",
   ["page"]=1,
   ["url"]="../images/simple-001-exported-1.svg",
   ["used"]="simple-001-exported-1.svg",
   ["width"]="54.380pt",
  },
  ["image>2"]={
   ["element"]="image",
   ["height"]="86.842pt",
   ["hover"]="",
   ["id"]="simple-001-image-2",
   ["name"]="cow.pdf",
   ["namespace"]="",
   ["page"]=1,
   ["url"]="../images/cow.svg",
   ["used"]="",
   ["width"]="115.789pt",
  },
 },
 ["language"]="en",
 ["metadata"]={},
 ["name"]="simple-001",
 ["stylepath"]="styles",
 ["styles"]={ "simple-001-defaults.css", "simple-001-images.css", "simple-001-fonts.css", "simple-001-styles.css" },
 ["title"]="simple-001",
 ["xhtmlfiles"]={ "simple-001-tag.xhtml" },
 ["xmlfiles"]={ "simple-001-raw.xml" },
}