return {
 ["htmlfiles"]={ "export-011-div.html" },
 ["htmlroot"]="export-011-div.html",
 ["identifier"]="f21d4352-4b33-b046-6b66-355b1abb8534",
 ["imagefile"]="styles/export-011-images.css",
 ["imagepath"]="images",
 ["images"]={
  ["image>1"]={
   ["element"]="image",
   ["height"]="3.000cm",
   ["id"]="image-1",
   ["name"]="export-011-exported-1.svg",
   ["namespace"]="",
   ["page"]=1,
   ["url"]="../images/export-011-exported-1.svg",
   ["used"]="export-011-exported-1.svg",
   ["width"]="3.000cm",
  },
  ["image>2"]={
   ["element"]="image",
   ["height"]="3.000cm",
   ["id"]="image-2",
   ["name"]="export-011-exported-2.svg",
   ["namespace"]="",
   ["page"]=1,
   ["url"]="../images/export-011-exported-2.svg",
   ["used"]="export-011-exported-2.svg",
   ["width"]="3.000cm",
  },
  ["image>3"]={
   ["element"]="image",
   ["height"]="3.000cm",
   ["id"]="image-3",
   ["name"]="export-011-exported-3.svg",
   ["namespace"]="",
   ["page"]=1,
   ["url"]="../images/export-011-exported-3.svg",
   ["used"]="export-011-exported-3.svg",
   ["width"]="3.000cm",
  },
 },
 ["language"]="en",
 ["metadata"]={},
 ["name"]="export-011",
 ["stylepath"]="styles",
 ["styles"]={ "export-011-defaults.css", "export-011-images.css", "export-011-fonts.css", "export-011-styles.css" },
 ["title"]="export-011",
 ["xhtmlfiles"]={ "export-011-tag.xhtml" },
 ["xmlfiles"]={ "export-011-raw.xml" },
}